from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from core.model.buildings import LandingPadState, SupplyRouteState
from core.model.units import UnitState


class LogisticsPort(Protocol):
    """Interface used by logistics services to interact with gameplay session state."""

    def landing_pads(self) -> Mapping[str, LandingPadState]: ...

    def objective_status(self) -> Mapping[str, bool]: ...

    def refresh_transport_geometry(self, landing_pad: LandingPadState) -> None: ...

    def start_transport_for_landing_pad(self, landing_pad: LandingPadState) -> None: ...

    def advance_transport(self, landing_pad: LandingPadState, elapsed_seconds: float) -> None: ...

    def supply_route_ids(self) -> tuple[str, ...]: ...

    def supply_route_by_id(self, route_id: str) -> SupplyRouteState | None: ...

    def find_unit_by_id(self, unit_id: str) -> UnitState | None: ...

    def remove_supply_route(self, route_id: str) -> None: ...

    def refresh_supply_route(self, route: SupplyRouteState, *, elapsed_seconds: float = 0.0) -> None: ...
